### ISSUE TITLE
请问可以用在linux系统上吗？

### ISSUE THREAD

**Issue by panxin801** [cpuimage/WebRTC_NS#4]
您好，请问这个项目可以使用在linux系统上吗？
期待您的回复，谢谢。

**Comment by cpuimage** [comment]
@panxin801 与平台无关,可以用在linux上,不过现在这个版本还有点bug.

**Comment by panxin801** [comment]
> @panxin801 与平台无关,可以用在linux上,不过现在这个版本还有点bug.

好的，谢谢啦。那我可以试试。

**Comment by leijue222** [comment]
> 示例具体流程为：
> 
> 加载wav(拖放wav文件到可执行文件上)->重采样降噪->保存wav

@cpuimage 请问如何指定wav音频文件以运行main.h进行降噪？
我在ubuntu和win10下直接拖拽都不行哦。
应该是我弄混了运行方式，能麻烦您再指导一下吗？

**Comment by cpuimage** [comment]
@leijue222 你必须先编译成可执行文件。Windows下 例如: ns.exe
