### ISSUE TITLE
音频降噪将时间变为两倍

### ISSUE THREAD

**Issue by neil3212080** [cpuimage/WebRTC_NS#5]
你好 在使用的时候，我传入一个16000的音频，音频在经过处理后声音发生了改变拉长了。
[降噪前后音频.zip](https://github.com/cpuimage/WebRTC_NS/files/2908484/default.zip)

**Comment by neil3212080** [comment]
而且在处理的时候 也改变了原本的声音 emmm 请问 您知道这是什么原因吗

**Comment by cpuimage** [comment]
@neil3212080 你的样本是个双通道的音频文件,代码里默认作为单通道处理,需要稍微改下代码,做下多通道音频文件的适配.稍后我提交下修改后的代码.

**Comment by cpuimage** [comment]
@neil3212080 已经提交修改了.
