### ISSUE TITLE
在arm设备上速度异常慢

### ISSUE THREAD

**Issue by tunmx** [cpuimage/WebRTC_NS#7]
作者您好，请问您有遇到过交叉编译到arm设备上后降噪速度非常慢的问题吗，这边试了一下rk1126的板子，3秒钟左右的音频需要10几秒的时间

**Comment by cpuimage** [comment]
> 作者您好，请问您有遇到过交叉编译到arm设备上后降噪速度非常慢的问题吗，这边试了一下rk1126的板子，3秒钟左右的音频需要10几秒的时间

确认一下是不是采用 Release 编译。

**Comment by tunmx** [comment]
确认了 确实是忘记开启release编译了 多谢大佬！
